Stma-12 Add workflow for enforcing branch names (#17)
* Test change

* Update github action for branch name

* Only enforce branch names for pull requests

* Print branch name if incorrect

* branch name should start with lower case

* Update github action to check branch_name

* Try different template

diff --git a/.github/workflows/enforce_branch_names.yml b/.github/workflows/enforce_branch_names.yml
--- a/.github/workflows/enforce_branch_names.yml
+++ b/.github/workflows/enforce_branch_names.yml
@@ -1,13 +1,22 @@
-name: 'Enforce Branch Names'
-on: [push, pull_request]
+name: 'Branch Name Check on PR'
+
+on:
+  pull_request:
+    types: [opened, reopened, synchronize]
 
 jobs:
   check-branch-name:
     runs-on: ubuntu-latest
     steps:
-    - name: Check Branch Name
-      run: |
-        if [[ ! $GITHUB_REF =~ ^refs/heads/STMA-[0-9]+$ ]]; then
-          echo "Branch name does not follow the 'STMA-<issue_number>' pattern"
-          exit 1
-        fi
+      - name: Check branch name
+        run: |
+          BRANCH_NAME=${GITHUB_HEAD_REF}
+          PATTERN="^stma-[0-9]+"
+
+          if [[ ! $BRANCH_NAME =~ $PATTERN ]]; then
+            echo "Invalid branch name: $BRANCH_NAME"
+            echo "Branch name does not follow the 'stma-xxx' pattern"
+            exit 1
+          else
+            echo "Branch name $BRANCH_NAME is valid."
+          fi
